# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Push Docker image

on: push

jobs:
  build-container:
    name: buildcontainer
    runs-on: ubuntu-latest
    steps:
      # - name: Check out code
      #   uses: actions/checkout@v3 
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # https://stackoverflow.com/questions/76313084/github-workflow-action-docker-compose-build-push-does-nothing-no-errors-but
      - name: Build and push
        run: |
          # docker compose build --build-arg TAG_NAME=${{ secrets.DOCKER_USERNAME }}-${{ github.run_number }} && \
          # docker compose push
          echo Welcome to Team 4 Deployment
